import {render,screen,waitFor,fireEvent} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter,Routes,Route} from 'react-router';
import {beforeEach,expect,it,vi} from 'vitest';
import {DashboardShell} from '../community/workspace';
import {Avatar,CommunityAccountDashboard,CommunityProfilePage,MyContributions} from '../community/account';
import {validateAvatar} from '../../../lib/community-profile';
const api=vi.hoisted(()=>({get:vi.fn(),save:vi.fn(),counts:vi.fn(),activeCount:vi.fn(),contributions:vi.fn(),avatar:vi.fn(),replaceAvatar:vi.fn(),removeAvatar:vi.fn()}));
vi.mock('../../../lib/community-profile',async()=>({...await vi.importActual('../../../lib/community-profile'),profileApi:api}));
vi.mock('../../contexts/AuthContext',()=>({useAuth:()=>({user:{id:'author'},isLoading:false})}));
vi.mock('../navbar',()=>({Navbar:()=>null}));
vi.mock('../../../lib/supabase-community',async()=>({...await vi.importActual('../../../lib/supabase-community'),communityApi:{reputation:async()=>[],taxonomy:async()=>({categories:[]})}}));
const profile={user_id:'author',display_name:'Example author',bio:'Fictional bio',expertise:['Cloud'],is_public:false,avatar_path:null};
function page(path:string){return render(<MemoryRouter initialEntries={[path]}><Routes><Route element={<DashboardShell/>}><Route path="/dashboard" element={<CommunityAccountDashboard/>}/></Route><Route path="/profile" element={<CommunityProfilePage/>}/><Route path="/people/:id" element={<CommunityProfilePage/>}/><Route path="/my-problems" element={<MyContributions kind="problems"/>}/></Routes></MemoryRouter>);}
beforeEach(()=>{Object.values(api).forEach(m=>m.mockReset());api.get.mockResolvedValue(profile);api.counts.mockResolvedValue({problems:2,solutions:3,accepted:1});api.activeCount.mockResolvedValue(1);api.contributions.mockResolvedValue([]);});
it('places the five workspace links above the dashboard content and keeps profile editing on the identity card',async()=>{page('/dashboard');expect(await screen.findByRole('link',{name:'Edit your profile'})).toHaveAttribute('href','/profile');const tabs=screen.getByRole('navigation',{name:'Your workspace'});expect(tabs).toHaveTextContent('Overview');expect(tabs).toHaveTextContent('Reputation history');expect(tabs.compareDocumentPosition(document.querySelector('.workspace-grid')!)).toBe(Node.DOCUMENT_POSITION_FOLLOWING);expect(screen.queryByRole('link',{name:'My profile'})).not.toBeInTheDocument();expect(document.querySelector('.workspace-stats')).toBeNull();expect(api.counts).not.toHaveBeenCalled();});
it('filters private drafts and provides resume links but never edit links for solved evidence',async()=>{api.contributions.mockResolvedValue([{id:'draft',problem_id:'draft',title:'Private case',summary:'',state:'open',visibility:'draft',accepted:false,is_example:false,created_at:'2026-09-26'}]);page('/my-problems?state=draft');expect(await screen.findByRole('link',{name:'Resume draft'})).toHaveAttribute('href','/problem/draft/edit');expect(api.contributions).toHaveBeenCalledWith('author','problems','draft',0,false);});
it('shows recoverable loading and error states',async()=>{api.get.mockRejectedValueOnce(new Error('Offline'));page('/dashboard');expect(screen.getAllByRole('status').length).toBeGreaterThan(0);expect(await screen.findByRole('alert')).toHaveTextContent('Offline');await userEvent.click(screen.getByRole('button',{name:'Try again'}));expect(await screen.findByRole('heading',{name:'Example author'})).toBeInTheDocument();});
it('uses a display name for community identity and preserves the private login identifier',async()=>{api.get.mockResolvedValue({...profile,username:'private-login'});api.save.mockImplementation(async p=>p);page('/profile');await screen.findByLabelText('Display name');expect(screen.queryByLabelText('Username')).not.toBeInTheDocument();await userEvent.clear(screen.getByLabelText('Display name'));await userEvent.type(screen.getByLabelText('Display name'),'New name');await userEvent.click(screen.getByLabelText('Publish my profile and picture'));await userEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText('Profile saved.')).toBeInTheDocument();expect(api.save).toHaveBeenCalledWith(expect.objectContaining({display_name:'New name',username:'private-login',is_public:true}));expect(api.contributions).toHaveBeenCalledWith('author','problems','',0,true);});
it('never shows editing controls or history for an unavailable public profile',async()=>{api.get.mockResolvedValue(null);page('/people/other');expect(await screen.findByText('This profile is private or has not been created.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Save profile'})).not.toBeInTheDocument();expect(api.contributions).not.toHaveBeenCalled();});
it('validates avatar type and size before decoding or uploading',()=>{expect(()=>validateAvatar({type:'image/svg+xml',size:10})).toThrow('PNG');expect(()=>validateAvatar({type:'image/png',size:6*1024*1024})).toThrow('5 MB');expect(()=>validateAvatar({type:'image/webp',size:100})).not.toThrow();});


it('recovers an unavailable avatar on returning to the tab',async()=>{api.avatar.mockRejectedValueOnce(new Error('Expired')).mockResolvedValue('https://example.test/renewed.webp');render(<Avatar profile={{...profile,avatar_path:'author/avatar.webp'}}/>);expect(await screen.findByRole('status')).toHaveTextContent('Picture temporarily unavailable');fireEvent.focus(window);expect(await screen.findByRole('img')).toHaveAttribute('src','https://example.test/renewed.webp');expect(screen.queryByRole('status')).not.toBeInTheDocument();});
