import {useEffect,useState,type FormEvent} from 'react';
import {Link,useParams,useSearchParams} from 'react-router';
import {useAuth} from '../../contexts/AuthContext';
import {profileApi,blankProfile,type CommunityProfile,type Contribution,type ContributionKind} from '../../../lib/community-profile';
import {communityApi,communityError} from '../../../lib/supabase-community';
import {CommunityLayout,ErrorNotice,TextField} from './shared';

export function AccountNav(){return <nav aria-label="Your workspace" className="community-actions"><Link to="/dashboard">Overview</Link><Link to="/my-problems">My problems</Link><Link to="/my-solutions">My solutions</Link><Link to="/my-solutions?accepted=1">Accepted fixes</Link><Link to="/profile">My profile</Link><Link to="/leaderboard">Reputation history</Link></nav>;}
function Avatar({profile}:{profile:CommunityProfile}){
 const [url,setUrl]=useState(''),[error,setError]=useState(false);
 useEffect(()=>{let active=true;setUrl('');setError(false);if(profile.avatar_path)profileApi.avatar(profile.avatar_path).then(u=>{if(active)setUrl(u);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[profile.avatar_path]);
 return <>{url?<img className="community-avatar" src={url} alt={`${profile.display_name||'Contributor'} profile picture`} onError={()=>{setUrl('');setError(true);}}/>:<div className="community-avatar community-avatar-fallback" aria-label="No profile picture">{(profile.display_name||'?').slice(0,1).toUpperCase()}</div>}{error&&<p>Picture unavailable. Refresh to retry.</p>}</>;
}
function Identity({profile}:{profile:CommunityProfile}){return <section className="dashboard-card community-card board-panel"><p className="board-kicker">Community identity</p><Avatar profile={profile}/><h2>{profile.display_name||'Community contributor'}</h2><p className="community-copy">{profile.bio||'No bio yet.'}</p><h3>Areas of expertise</h3>{profile.expertise.length?<ul>{profile.expertise.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>No areas added yet.</p>}</section>;}
function ContributionRows({rows,kind,editable=false}:{rows:Contribution[];kind:ContributionKind;editable?:boolean}){return <div className="community-stack">{rows.map(r=><article key={r.id} className="board-panel community-card"><span className="board-pill">{r.visibility==='draft'?'Private draft':r.state}</span>{r.is_example&&<p>Fictional example — outcomes are simulated.</p>}<h2><Link to={`/problem/${r.problem_id}${kind==='problems'?'':`#solution-${r.id}`}`}>{kind==='problems'?r.title:r.summary}</Link></h2>{kind!=='problems'&&<p>On: {r.title} · {r.accepted?(r.is_example?'Illustrative accepted outcome':'Accepted by the author'):'Proposed solution'}</p>}{kind==='problems'&&<p className="community-preview">{r.summary||'Draft in progress'}</p>}<p className="community-muted">{new Date(r.created_at).toLocaleDateString()}</p>{editable&&kind==='problems'&&r.state!=='solved'&&<Link to={`/problem/${r.id}/edit`}>{r.visibility==='draft'?'Resume draft':'Edit problem'}</Link>}</article>)}</div>;}
export function ContributionList({id,kind,publicOnly=false,editable=false}:{id:string;kind:ContributionKind;publicOnly?:boolean;editable?:boolean}){
 const [params,setParams]=useSearchParams();const state=kind==='problems'?(params.get('state')||''):'';
 const offset=Math.max(0,Math.min(100000,Number(params.get('offset'))||0));
 const [rows,setRows]=useState<Contribution[]|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setRows(null);setError('');profileApi.contributions(id,kind,state,offset,publicOnly).then(r=>{if(active)setRows(r);}).catch(e=>{if(active)setError(communityError(e));});return()=>{active=false;};},[id,kind,state,offset,publicOnly,retry]);
 function change(key:string,value:string){const p=new URLSearchParams(params);p.set(key,value);if(key!=='offset')p.delete('offset');setParams(p);}
 return <>{kind==='problems'&&<label className="community-field">Problem state<select value={state} onChange={e=>change('state',e.target.value)}><option value="">All states</option>{(publicOnly?['open','testing','solved','closed']:['draft','open','testing','solved','closed']).map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></label>}
 {error?<ErrorNotice error={error} retry={()=>setRetry(n=>n+1)}/>:!rows?<p role="status">Loading contributions…</p>:<>{!rows.length?<p>No {kind==='accepted'?'accepted fixes':kind} to show{state?` in ${state}`:''}.</p>:<ContributionRows rows={rows.slice(0,20)} kind={kind} editable={editable}/>}<nav aria-label="Contribution pages" className="community-actions"><button disabled={!offset} onClick={()=>change('offset',String(Math.max(0,offset-20)))}>Previous page</button><span>Page {Math.floor(offset/20)+1}</span><button disabled={rows.length<=20} onClick={()=>change('offset',String(offset+20))}>Next page</button></nav></>}
 </>;
}
function CategoryReputation({id}:{id:string}){
 const [data,setData]=useState<{rows:Awaited<ReturnType<typeof communityApi.reputation>>;names:Record<string,string>}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError('');Promise.all([communityApi.reputation(id),communityApi.taxonomy()]).then(([rows,t])=>{if(active)setData({rows,names:Object.fromEntries(t.categories.map(c=>[c.id,c.name]))});}).catch(e=>{if(active)setError(communityError(e));});return()=>{active=false;};},[id,retry]);
 return <section className="board-panel community-card"><h2>Category reputation</h2><p>Public, non-example contributions. Upvotes and acceptance are distinct signals.</p>{error?<ErrorNotice error={error} retry={()=>setRetry(n=>n+1)}/>:!data?<p role="status">Loading reputation…</p>:!data.rows.length?<p>No reputation awards yet.</p>:<ul>{data.rows.map(r=><li key={r.category_id}>{data.names[r.category_id]}: <strong>{r.points} points</strong></li>)}</ul>}<Link to="/leaderboard">View reputation and event history</Link></section>;
}
export function CommunityAccountDashboard(){
 const {user}=useAuth();const id=user!.id;
 const [data,setData]=useState<{profile:CommunityProfile;counts:{problems:number;solutions:number;accepted:number};recent:Contribution[];recentSolutions:Contribution[]}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError('');Promise.all([profileApi.get(id),profileApi.counts(id,false),profileApi.contributions(id,'problems','',0,false),profileApi.contributions(id,'solutions','',0,false)]).then(([profile,counts,recent,recentSolutions])=>{if(active)setData({profile:profile||blankProfile(id),counts,recent,recentSolutions});}).catch(e=>{if(active)setError(communityError(e));});return()=>{active=false;};},[id,retry]);
 return <CommunityLayout title="Your dashboard"><div className="dashboard-page-header"><div><p className="board-kicker">Your community workspace</p><h1>Your dashboard</h1><p>Track your questions, proposed solutions and tested fixes.</p></div><Link className="community-action" to="/post-problem">Post a problem</Link></div><AccountNav/>
 {error?<ErrorNotice error={error} retry={()=>setRetry(n=>n+1)}/>:!data?<p role="status">Loading dashboard…</p>:<><div className="community-account-stats">{([['My problems',data.counts.problems,'/my-problems'],['My solutions',data.counts.solutions,'/my-solutions'],['Accepted fixes',data.counts.accepted,'/my-solutions?accepted=1']] as const).map(([label,n,url])=><Link className="dashboard-stat-card community-stat" to={url} key={label} aria-label={`${label}: ${n}. View full list`}><span>{label}</span><strong>{n}</strong><span>View full list →</span></Link>)}</div><p>Counts include fictional examples. Solutions on unavailable discussions are excluded.</p><div className="dashboard-grid"><aside className="community-stack"><Identity profile={data.profile}/><Link to="/profile">Edit your profile and picture</Link><CategoryReputation id={id}/></aside><section className="community-stack"><h2>Recent problems</h2>{data.recent.length?<ContributionRows rows={data.recent.slice(0,3)} kind="problems" editable/>:<p>No problems yet. Start a private draft when you are ready.</p>}<Link to="/my-problems">View all problems and drafts</Link><h2>Recent solutions</h2>{data.recentSolutions.length?<ContributionRows rows={data.recentSolutions.slice(0,3)} kind="solutions"/>:<p>No solutions yet. Share a proposed fix on an open problem.</p>}<Link to="/my-solutions">View all submitted solutions</Link><Link to="/moderation">Moderator review</Link></section></div></>}
 </CommunityLayout>;
}
export function MyContributions({kind}:{kind:'problems'|'solutions'}){const {user}=useAuth();const [params]=useSearchParams();const selected=kind==='solutions'&&params.get('accepted')==='1'?'accepted':kind;return <CommunityLayout title={selected==='accepted'?'Accepted fixes':`My ${kind}`}><h1>{selected==='accepted'?'Accepted fixes':`My ${kind}`}</h1><AccountNav/><p>{kind==='problems'?'Drafts are private. Use the state filter to find work to resume.':'Your answers on discussions you can currently access. Acceptance means the problem author confirmed the outcome.'}</p><ContributionList id={user!.id} kind={selected} editable={kind==='problems'}/></CommunityLayout>;}
export function CommunityProfilePage(){
 const {user}=useAuth();const {id:publicId}=useParams();const id=publicId||user!.id;const own=!publicId;const [params,setParams]=useSearchParams();
 const [profile,setProfile]=useState<CommunityProfile|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setProfile(null);setError('');profileApi.get(id).then(p=>{if(active)setProfile(p||(own?blankProfile(id):null));}).catch(e=>{if(active)setError(communityError(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[id,own,retry]);
 const kind:ContributionKind=params.get('kind')==='solutions'?'solutions':params.get('kind')==='accepted'?'accepted':'problems';
 return <CommunityLayout title={own?'Your profile':'Community profile'}><h1>{own?'Your profile':'Community profile'}</h1>{own&&<AccountNav/>}{error?<ErrorNotice error={error} retry={()=>setRetry(n=>n+1)}/>:loading?<p role="status">Loading profile…</p>:!profile||(!own&&!profile.is_public)?<p>This profile is private or has not been created.</p>:<><div className="dashboard-grid"><aside className="community-stack"><Identity profile={profile}/><CategoryReputation id={id}/></aside><div>{own?<ProfileEditor key={id} profile={profile} onSaved={setProfile}/>:<p>Only information this contributor chose to publish is shown. Expertise is self-described.</p>}{own&&profile.is_public&&<Link to={`/people/${id}`}>Preview public profile</Link>}<h2>Public contribution history</h2><p>Public discussions remain public even when your profile is private. Drafts are never listed here.</p><label className="community-field">Contribution type<select value={kind} onChange={e=>setParams({kind:e.target.value})}><option value="problems">Problems</option><option value="solutions">Solutions</option><option value="accepted">Accepted fixes</option></select></label><ContributionList id={id} kind={kind} publicOnly/></div></div></>}
 </CommunityLayout>;
}
function ProfileEditor({profile,onSaved}:{profile:CommunityProfile;onSaved:(p:CommunityProfile)=>void}){
 const [name,setName]=useState(profile.display_name),[bio,setBio]=useState(profile.bio),[expertise,setExpertise]=useState(profile.expertise.join(', ')),[publicProfile,setPublic]=useState(profile.is_public),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function run(action:()=>Promise<CommunityProfile>,message:string){setBusy(true);setError('');setMessage('');try{onSaved(await action());setMessage(message);}catch(e){setError(communityError(e));}finally{setBusy(false);}}
 function save(e:FormEvent){e.preventDefault();const areas=[...new Set(expertise.split(',').map(x=>x.trim()).filter(Boolean))];if(areas.length>12){setError('Choose at most 12 areas of expertise.');return;}void run(()=>profileApi.save({...profile,display_name:name,bio,expertise:areas,is_public:publicProfile}),'Profile saved.');}
 return <section className="board-panel community-card"><h2>Edit profile</h2><p>Your email and account settings are never part of this public profile. Publishing is optional.</p><form onSubmit={save}><fieldset disabled={busy}><TextField label="Display name" value={name} onChange={setName} multiline={false} maxLength={80}/><TextField label="Short bio" value={bio} onChange={setBio} maxLength={500}/><TextField label="Areas of expertise (comma separated, up to 12)" value={expertise} onChange={setExpertise} maxLength={500}/><label className="community-actions"><input type="checkbox" checked={publicProfile} onChange={e=>setPublic(e.target.checked)}/>Publish my profile and picture</label><button type="submit">Save profile</button></fieldset></form><h3>Profile picture</h3><p>PNG, JPEG or WebP, up to 5 MB and 4096 pixels per side. Saved as a still image, up to 512 pixels, with original metadata removed. Previously shared image links may work for up to 60 seconds after making a profile private.</p><fieldset disabled={busy}><label className="community-field">Upload or replace picture<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(()=>profileApi.replaceAvatar(profile,file),'Picture updated.');}}/></label>{profile.avatar_path&&<button type="button" onClick={()=>void run(()=>profileApi.removeAvatar(profile),'Picture removed.')}>Remove picture</button>}</fieldset>{busy&&<p role="status">Saving…</p>}{message&&<p role="status">{message}</p>}{error&&<ErrorNotice error={error}/>}</section>;
}
