import { useEffect, useState, type FormEvent } from 'react';
import { communityApi, communityError } from '../../../lib/supabase-community';
import { CommunityLayout, ErrorNotice, TextField } from './shared';
import { useAuth } from '../../contexts/AuthContext';

export function ReportControl({target,label}:{target:{problem_id?:string;solution_id?:string;comment_id?:string};label:string}){
 const [open,setOpen]=useState(false),[reason,setReason]=useState(''),[details,setDetails]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await communityApi.report(target,reason.trim(),details.trim());setDone(true);setOpen(false);}catch(e){setError(communityError(e));}finally{setBusy(false);}}
 return <div className="community-stack">{done?<p role="status">Report sent privately to moderators.</p>:<button onClick={()=>setOpen(v=>!v)} aria-expanded={open}>Report {label}</button>}
 {open&&<form onSubmit={submit} aria-label={`Report ${label}`}><p>Only you and moderators can read your report. Do not include passwords or customer information.</p><fieldset disabled={busy}><TextField label="Report reason" value={reason} onChange={setReason} required maxLength={200}/><TextField label="Private report details" value={details} onChange={setDetails}/><button type="submit">Send report</button><button type="button" onClick={()=>setOpen(false)}>Cancel</button></fieldset></form>}{error&&<ErrorNotice error={error}/>}</div>;
}
export function ModeratorPage(){
 const {user}=useAuth();const [allowed,setAllowed]=useState<boolean|null>(null),[rows,setRows]=useState<Awaited<ReturnType<typeof communityApi.reports>>>([]),[reviews,setReviews]=useState<Awaited<ReturnType<typeof communityApi.reviews>>>([]),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setAllowed(null);setRows([]);setError('');(async()=>{try{const ok=await communityApi.moderator();if(!active)return;setAllowed(ok);if(ok){const [r,v]=await Promise.all([communityApi.reports(),communityApi.reviews()]);if(active){setRows(r);setReviews(v);}}}catch(e){if(active)setError(communityError(e));}})();return()=>{active=false;};},[user?.id,retry]);
 return <CommunityLayout><h1>Moderator review</h1>{error?<ErrorNotice error={error} retry={()=>setRetry(n=>n+1)}/>:allowed===null?<p role="status">Checking moderator access…</p>:!allowed?<p>You do not have moderator permission.</p>:<><p>Private reports, latest 100. Hiding a reported discussion removes it and its answers from public access; it does not delete content. Private drafts remain private.</p>{!rows.length?<p>No reports to review.</p>:rows.map(r=><Review key={r.id} report={r} review={reviews.find(v=>v.report_id===r.id)} onSaved={()=>setRetry(n=>n+1)}/>)}</>}</CommunityLayout>;
}
function Review({report:r,review,onSaved}:{report:Awaited<ReturnType<typeof communityApi.reports>>[number];review?:Awaited<ReturnType<typeof communityApi.reviews>>[number];onSaved:()=>void}){
 const [notes,setNotes]=useState(review?.private_notes || ''),[status,setStatus]=useState(review?.status || 'reviewing'),[action,setAction]=useState('review'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await communityApi.review(r.id,status,notes.trim(),action);onSaved();}catch(e){setError(communityError(e));}finally{setBusy(false);}}
 return <article className="board-panel community-card community-stack"><h2>{r.reason}</h2><p>{r.target_excerpt}</p><p>{r.details}</p><form onSubmit={submit}><fieldset disabled={busy}><label className="community-field">Review status<select aria-label="Review status" value={status} onChange={e=>setStatus(e.target.value)}><option value="reviewing">Reviewing</option><option value="dismissed">Dismissed</option><option value="actioned">Actioned</option></select></label><label className="community-field">Content action<select aria-label="Content action" value={action} onChange={e=>setAction(e.target.value)}><option value="review">Leave visibility unchanged</option><option value="hide">Hide reported discussion</option><option value="restore">Restore public discussion</option></select></label><TextField label="Moderator-only notes" value={notes} onChange={setNotes} required maxLength={20000}/><button type="submit">Save review</button></fieldset></form>{error&&<ErrorNotice error={error}/>}</article>;
}
